In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv("Balon.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['YELLOW' 'SMALL' 'STRETCH' 'ADULT']
 ['YELLOW' 'SMALL' 'STRETCH' 'CHILD']
 ['YELLOW' 'SMALL' 'DIP' 'ADULT']
 ['YELLOW' 'SMALL' 'DIP' 'CHILD']
 ['YELLOW' 'SMALL' 'DIP' 'CHILD']
 ['PURPLE' 'LARGE' 'STRETCH' 'ADULT']
 ['PURPLE' 'LARGE' 'STRETCH' 'CHILD']
 ['PURPLE' 'SMALL' 'DIP' 'CHILD']
 ['PURPLE' 'SMALL' 'DIP' 'CHILD']
 ['PURPLE' 'SMALL' 'STRETCH' 'CHILD']]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 'SMALL' 'STRETCH' 'ADULT']
 [0.0 1.0 'SMALL' 'STRETCH' 'CHILD']
 [0.0 1.0 'SMALL' 'DIP' 'ADULT']
 [0.0 1.0 'SMALL' 'DIP' 'CHILD']
 [0.0 1.0 'SMALL' 'DIP' 'CHILD']
 [1.0 0.0 'LARGE' 'STRETCH' 'ADULT']
 [1.0 0.0 'LARGE' 'STRETCH' 'CHILD']
 [1.0 0.0 'SMALL' 'DIP' 'CHILD']
 [1.0 0.0 'SMALL' 'DIP' 'CHILD']
 [1.0 0.0 'SMALL' 'STRETCH' 'CHILD']]


In [ ]:
labelEncoder = LabelEncoder()
x[:, 2] = labelEncoder.fit_transform(x[:, 2])
x[:, 3] = labelEncoder.fit_transform(x[:, 3])
x[:, 4] = labelEncoder.fit_transform(x[:, 4])

In [ ]:
print(x)

[[0.0 1.0 1 1 0]
 [0.0 1.0 1 1 1]
 [0.0 1.0 1 0 0]
 [0.0 1.0 1 0 1]
 [0.0 1.0 1 0 1]
 [1.0 0.0 0 1 0]
 [1.0 0.0 0 1 1]
 [1.0 0.0 1 0 1]
 [1.0 0.0 1 0 1]
 [1.0 0.0 1 1 1]]


In [ ]:
y = labelEncoder.fit_transform(y)

In [ ]:
print(y)

[1 1 1 0 0 1 1 0 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[1.0 0.0 0 1 1]
 [0.0 1.0 1 0 1]
 [0.0 1.0 1 1 0]
 [0.0 1.0 1 0 1]
 [0.0 1.0 1 1 1]
 [1.0 0.0 1 0 1]
 [1.0 0.0 1 0 1]
 [1.0 0.0 0 1 0]]


In [ ]:
print(x_test)

[[0.0 1.0 1 0 0]
 [1.0 0.0 1 1 1]]


In [ ]:
print(y_train)

[1 0 1 0 1 0 0 1]


In [ ]:
print(y_test)

[1 1]
